apiVersion: "v1"
kind: "ReplicationController"
metadata:
  labels:
    name: "heapster"
  name: "monitoring-heapster-controller"
spec:
  replicas: 1
  selector:
    name: "heapster"
  template:
    metadata:
      labels:
        name: "heapster"
    spec:
      containers:
        -
          image: suyogbarve/heapster:canary
          name: "heapster"
          command:
            - "/heapster"
            - "--source=kubernetes:http://172.16.164.159:8080?inClusterConfig=false&useServiceAccount=false&auth="
            - "--sink=log"
