apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginxplus
  name: nginxplus-rc
  namespace: kube-infra
  selfLink: /api/v1/namespaces/default/replicationcontrollers/nginxplus-rc
  uid: 6712746e-65bf-11e6-989a-fa163e91bede
spec:
  replicas: 1
  selector:
    app: nginxplus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxplus
    spec:
      containers:
      - image: suyogbarve/nginx-plus-trial:1.0
        imagePullPolicy: IfNotPresent
        name: nginxplus
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          name: http-alt
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: etc-nginx-confd
      dnsPolicy: ClusterFirst
      nodeSelector:
        role: nginxplus
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/nginx/conf.d
        name: etc-nginx-confd
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1